/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/base': RouteRecordInfo<
      '/base',
      '/base',
      Record<never, never>,
      Record<never, never>,
      | '/base/login'
      | '/base/select_[mode]'
      | '/base/splash'
    >,
    '/base/login': RouteRecordInfo<
      '/base/login',
      '/base/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/base/select_[mode]': RouteRecordInfo<
      '/base/select_[mode]',
      '/base/select_:mode',
      { mode: ParamValue<true> },
      { mode: ParamValue<false> },
      | never
    >,
    '/base/splash': RouteRecordInfo<
      '/base/splash',
      '/base/splash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blur': RouteRecordInfo<
      '/blur',
      '/blur',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup': RouteRecordInfo<
      '/setup',
      '/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/theming': RouteRecordInfo<
      '/theming',
      '/theming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/base.vue': {
      routes:
        | '/base'
        | '/base/login'
        | '/base/select_[mode]'
        | '/base/splash'
      views:
        | 'default'
    }
    'src/pages/base/login.vue': {
      routes:
        | '/base/login'
      views:
        | never
    }
    'src/pages/base/select_[mode].vue': {
      routes:
        | '/base/select_[mode]'
      views:
        | never
    }
    'src/pages/base/splash.vue': {
      routes:
        | '/base/splash'
      views:
        | never
    }
    'src/pages/blur.vue': {
      routes:
        | '/blur'
      views:
        | never
    }
    'src/pages/setup.vue': {
      routes:
        | '/setup'
      views:
        | never
    }
    'src/pages/theming.vue': {
      routes:
        | '/theming'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
